services:
  - type: web
    name: baccarat-api
    env: python
    plan: free
    buildCommand: ""
    # startCommand 修正為 gunicorn app:app
    # 前面的 'app' 是你的檔名 (app.py)，後面的 'app' 是 Flask 實例名稱
    startCommand: gunicorn app:app
    autoDeploy: true
