services:
  - type: web
    name: baccarat-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --threads 2 --timeout 60"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GUNICORN_CMD_ARGS
        value: "--preload"
    # 添加模型文件處理
    buildFilter:
      paths:
        - "*.py"
        - "*.pkl"
        - "requirements.txt"
        - "*.txt"
